import org.ajoberstar.grgit.Grgit

// ################## plugin gradle ##################
plugins {
	id 'java'
	id 'eclipse'
	id 'org.ajoberstar.release-opinion' version '1.6.0'
	id 'application'
}

// ################## constants ##################
sourceCompatibility = 1.8
targetCompatibility = 1.8

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

// ################## java ##################
mainClassName='com.bee.Bee'

// ################## number version  ##################
release {
	grgit = Grgit.open(project.file('.'))
}

// ################## maven ##################
group='com.bee'

repositories {
    mavenCentral()
}

// ################## source sandbox ##################
sourceSets {
	main {
		java {
			srcDir 'src/main/java'
		}
	}
}

jar {
	manifest {
		attributes(
			"Main-Class": "com.bee.Bee",
			"Implementation-Title": "bee",
			"Implementation-Version": project.getVersion()
		)
	}
}

// ################## 'eclipse' plugin ##################
eclipse {
	classpath {
		downloadSources = true
		downloadJavadoc = false
	}
}

// ################## common dependencies ##################
dependencies {
	implementation 'info.picocli:picocli:4.6.1'
}
