Args = --add-opens java.base/java.util.regex=ALL-UNNAMED \
       -H:ReflectionConfigurationFiles=${.}/reflect-config.json \
       --initialize-at-build-time=com.bee \
       --initialize-at-run-time=com.bee.Node
